---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kubelet-serving-cert-approver.yaml
  - network-system.yaml
  - services.yaml
  - system-monitoring.yaml
  - home-automation.yaml
