---
apiVersion: metal.sidero.dev/v1alpha1
kind: ServerClass
metadata:
  name: hekate-master
spec:
  environmentRef:
    name: rpi4
  # bootFromDiskMethod: ipxe-sanboot
  configPatches:
    # - op: replace
    #   path: /machine/install/disk
    #   value: /dev/mmcblk1
    # #   # value: /dev/sda
    - op: replace
      path: /machine/install
      value:
        diskSelector:
          busPath: /system/container/ACPI0004:01/BRCME88C:00/mmc_host/*
    - op: add
      path: /machine/network
      value:
        interfaces:
          - interface: eth0
            dhcp: true
    - op: add
      path: /machine/kubelet/extraArgs
      value:
        rotate-server-certificates: true
    # - op: add
    #   path: /cluster/network/cni
    #   value:
    #     name: 'none'
    # # - op: add
    # #   path: /cluster/network/cni
    # #   value:
    # #     name: custom
    # #     urls:
    # #       - https://raw.githubusercontent.com/CodeHoschi/k8s-clusters/main/integrations/sidero/custom/cni/cilium-deployment.yaml
    # - op: add
    #   path: /cluster/proxy/disabled
    #   value: true
  selector:
    matchLabels:
      hekate-master: "true"
