---
apiVersion: metal.sidero.dev/v1alpha1
kind: ServerClass
metadata:
  name: heakte-worker
spec:
  # bootFromDiskMethod: ipxe-sanboot
  configPatches:
    # - op: replace
    #   path: /machine/install/disk
    #   value: /dev/mmcblk1
    - op: replace
      path: /machine/install
      value:
        diskSelector:
          type: SD
    - op: add
      path: /machine/network
      value:
        interfaces:
          - interface: eth0
            dhcp: true
    - op: add
      path: /machine/kubelet/extraArgs
      value:
        rotate-server-certificates: true
  selector:
    matchLabels:
      hekate-worker: "true"
