---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sync
  - truenas-workload-capi-sync.yaml
  # - hekate-capi-sync.yaml
  - cluster-settings.yaml
  - cluster-secrets.sops.yaml
