---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  # - ../../_base/core/
resources:
  - namespaces
  - kube-system
  - network-system
  - system-monitoring
  - nfs-subdir-external-provisioner
