---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../_base.reworkme/core/
resources:
  - network-system
  - kube-system
  - system-monitoring
# - namespaces
# - kubelet-serving-cert-approver
