---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network-system
resources:
  - helm-release.yaml
  # - custom-resources
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: metallb-config
    files:
      - config=metallb-config.yaml
