---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.16
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner-charts
        namespace: flux-system
      interval: 1h
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # image:
    #   repository: gcr.io/k8s-staging-sig-storage/nfs-subdir-external-provisioner
    #   tag: v4.0.2
    nfs:
      server: ${SECRET_NAS_IP}
      path: /volume1/kubedata
      mountOptions:
        - nfsvers=4
        - hard
        - noac
        - nocto
        - noacl
        - rsize=8192
        - wsize=8192
        - async
        - retrans=3
        - timeo=600
    storageClass:
      defaultClass: false
      # pathPattern: '${.PVC.namespace}-${.PVC.name}' # flux cannot resolve variable error
