---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apply-truenas-workload-cluster-namespaces
  namespace: flux-system
spec:
  interval: 10m
  # dependsOn:
  #   - name: apply-manage-flux
  kubeConfig:
    secretRef:
      name: truenas-workload-kubeconfig
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/truenas-workload/flux/namespaces
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
