---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apply-truenas-workload-cluster-repositories
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 10m0s
  kubeConfig:
    secretRef:
      name: truenas-workload-kubeconfig
  sourceRef:
    kind: GitRepository
    name: k8s-clusters
  path: ./clusters/truenas-workload/flux/repositories
  prune: true
  wait: true
