---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apply-truenas-workload-cluster-crds
  namespace: flux-system
spec:
  dependsOn:
    # - name: apply-cluster-config
    - name: apply-truenas-workload-cluster-repositories
    - name: apply-truenas-workload-cluster-manage-flux
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 10m0s
  kubeConfig:
    secretRef:
      name: truenas-workload-kubeconfig
  sourceRef:
    kind: GitRepository
    name: k8s-clusters
  path: ./clusters/truenas-workload/crds/
  prune: true
  wait: true
