---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings-hekate
  namespace: flux-system
data:
  CLUSTER_NAME: hekate
  CLUSTER_ID: "2"
  GATEWAY_IP: 10.200.0.1
  SVC_BLOCKY_ADDRESS: 192.168.1.243
  SVC_HOME_ASSISTANT_ADDRESS: 192.168.1.246
  SVC_PROMTAIL_ADDRESS: 192.168.1.243
