# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: user-home-automation-mosquitto
#   namespace: flux-system
# spec:
#   interval: 10m
#   path: ./manifests/hekate/apps/home-automation/mosquitto
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: k8s-clusters
#   wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: user-home-automation-emqx
  namespace: flux-system
spec:
  interval: 10m
  path: ./manifests/hekate/apps/home-automation/emqx
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-clusters
  wait: true
