---
apiVersion: metal.sidero.dev/v1alpha1
kind: Environment
metadata:
  name: rpi4
spec:
  initrd:
    url: https://github.com/siderolabs/talos/releases/download/v1.2.3/initramfs-arm64.xz
  kernel:
    url: https://github.com/siderolabs/talos/releases/download/v1.2.3/vmlinuz-arm64
    args:
      - console=ttyAMA0,115200
      - consoleblank=0
      - earlyprintk=ttyAMA0,115200
      - ima_appraise=fix
      - ima_hash=sha512
      - ima_template=ima-ng
      - init_on_alloc=1
      - initrd=initramfs.xz
      - nvme_core.io_timeout=4294967295
      - printk.devkmsg=on
      - pti=on
      - random.trust_cpu=on
      - slab_nomerge=
      - talos.platform=metal
      - talos.board=rpi_4
