---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: sidero-management-core
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: sidero-management-crds
  sourceRef:
    kind: GitRepository
    name: k8s-clusters
  path: ./manifests/sidero-management/core
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: Secret
        name: cluster-secrets-sidero-management
      - kind: ConfigMap
        name: cluster-settings-sidero-management
