---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  # name: apply-truenas-workload-orchestration-core
  name: truenas-workload-core
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: truenas-workload-crds
  kubeConfig:
    secretRef:
      name: truenas-workload-kubeconfig
  # path: ./clusters/truenas-workload/flux/orchestration/core
  path: ./manifests/truenas-workload/apps
  prune: true
  # wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings-truenas-workload
      - kind: Secret
        name: cluster-secrets-truenas-workload
